// Requirements
/*
    Create a library app with object constructor

    Books are gonna be stored in array
    * create constructor for books
    * add a separate fnc outside the constructor that takes some args to
    * create a book object with unique id
    * id can be generated by crypto.randomUUID()


*/


const library = [];

function Book(title, author, pages, isRead) {

    if (!new.target) throw Error('You must use the "new" operator to call the constructor!');

    this.id = crypto.randomUUID()
    this.title = title;
    this.author = author;
    this.pages = pages;
    this.isRead = isRead;
}


function addBookToLibrary(title, author, pages, isRead) {
    new_book = new Book(title, author, pages, isRead);
    console.log("Book created:", new_book);
    console.log("Library size:", library.length);


    return library.push(new_book);
}

function getUserInput(callback) {

    console.log("btn clicked!");
    let title = document.getElementById('title').value.trim();
    let author = document.getElementById('author').value.trim();
    let pages = document.getElementById('pages').value.trim();
    let isRead = document.querySelector("input[name='isRead']:checked").value === 'true';

    pages = parseInt(pages);

    return callback(title, author, pages, isRead)
}

function cardBuilder(book) {
    const card = document.createElement('div');
    card.className = 'card';

    card.innerHTML = `<div class="card">
                    <div class="card-img">
                        <img src="book-cover.webp" alt="Book Cover">
                    </div>
                    <div class="card-body">
                        <h3>Title: ${book.title}</h3>
                        <p>Author: ${book.author}</p>
                        <p>Pages: ${book.pages}</p>
                        <p class="is-read">Status: ${book.isRead ? 'Read' : 'Not read'} <span class="badge-pill">Read</span></p>
                    </div>
                    <div class="card-footer">
                        <button>Mark as Read</button>
                        <button>Remove</button>
                    </div>
                </div>
                `;
    return card
}


function renderBook() {
    const container = document.querySelector('.book-list');
    container.innerHTML = '';

    for (const book of library) {
        container.appendChild(cardBuilder(book))
    }
}

function toggleForm() {
    const form = document.getElementById('form');
    const overlay = document.getElementById('overlay');

    form.classList.toggle('hidden');
    overlay.classList.toggle('hidden');
}

/* Rendering */
document.addEventListener('DOMContentLoaded', function () {

    document.getElementById('add-book').addEventListener('click', () => {
        toggleForm()
    })

    document.getElementById('overlay').addEventListener('click', toggleForm);

    document.getElementById('form').addEventListener('submit', function (e) {
        e.preventDefault()
        getUserInput(function (title, author, pages, isRead) {
            addBookToLibrary(title, author, pages, isRead);
            renderBook();
        })
    })



})

