// Requirements
/*
    Create a library app with object constructor

    Books are gonna be stored in array
    * create constructor for books
    * add a separate fnc outside the constructor that takes some args to
    * create a book object with unique id
    * id can be generated by crypto.randomUUID()


*/


const library = [];

function Book(title, author, pages, isRead) {

    if (!new.target) throw Error('You must use the "new" operator to call the constructor!');

    this.id = crypto.randomUUID()
    this.title = title;
    this.author = author;
    this.pages = pages;
    this.isRead = isRead;
}

Book.prototype.toggleRead = function () {
    this.isRead = !this.isRead;
}


function addBookToLibrary(title, author, pages, isRead) {
    new_book = new Book(title, author, pages, isRead);
    console.log("Book created:", new_book);
    console.log("Library size:", library.length);


    return library.push(new_book);
}

function getUserInput(callback) {

    console.log("btn clicked!");
    let title = document.getElementById('title').value.trim();
    let author = document.getElementById('author').value.trim();
    let pages = document.getElementById('pages').value.trim();
    let isRead = false;

    pages = parseInt(pages);

    return callback(title, author, pages, isRead)
}

function cardBuilder(book) {
    const card = document.createElement('div');
    card.className = 'card';
    card.dataset.id = book.id

    card.innerHTML = `
                    <div class="card-img">
                        <img src="book-cover.webp" alt="Book Cover">
                    </div>
                    <div class="card-body">
                        <h3>Title: ${book.title}</h3>
                        <p>Author: ${book.author}</p>
                        <p>Pages: ${book.pages}</p>
                        <p class="is-read">Status: <span class="badge-pill ${book.isRead ? 'read' : 'not-read'}">${book.isRead ? 'Read' : 'Not read'}</span></p>
                    </div>
                    <div class="card-footer">
                        <button class="mark-as-read">Mark as Read</button>
                        <button class="rm-book">Remove</button>
                    </div>
                `;
    return card
}


function renderBook() {
    const container = document.querySelector('.book-list');
    container.innerHTML = '';

    for (const book of library) {
        container.appendChild(cardBuilder(book))
    }
}

function toggleForm() {
    const form = document.getElementById('form');
    const overlay = document.getElementById('overlay');

    form.classList.toggle('hidden');
    overlay.classList.toggle('hidden');
}

/* Rendering */
document.addEventListener('DOMContentLoaded', function () {

    document.getElementById('add-book').addEventListener('click', () => {
        toggleForm()
    })

    document.getElementById('overlay').addEventListener('click', toggleForm);

    document.getElementById('form').addEventListener('submit', function (e) {
        e.preventDefault()
        getUserInput(function (title, author, pages, isRead) {
            addBookToLibrary(title, author, pages, isRead);
            renderBook();
        })
    })

    document.querySelector('.book-list').addEventListener('click', (e) => {
        if (e.target.classList.contains('rm-book')) {

            const card = e.target.closest('.card');
            const id = card.dataset.id;

            const idx = library.findIndex(book => book.id === id)

            if (idx === -1) return;

            library.splice(idx, 1)

            renderBook()
            return;
        }

        if (e.target.classList.contains('mark-as-read')) {
            const card = e.target.closest('.card')
            const id = card.dataset.id;

            const book = library.find(book => book.id === id)
            if (!book) return;

            book.toggleRead()
            renderBook()
        }


    })

    renderBook()



})

